AutenticacionApp/urls.py
from django.urls import path


from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'AutenticacionApp'

urlpatterns = [

    path('', views.registro, name="Registro"),

    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('usuarios/<int:id_usuario>/actualizar/', views.actualizar_usuario, name='actualizar_usuario'),
    path('usuarios/<int:id_usuario>/eliminar/', views.eliminar_usuario, name='eliminar_usuario'),
    
]

FeriaVirtual/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    path('servicios/', include('ServiciosApp.urls')),
    path('registro/', include('AutenticacionApp.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),

    path('auth/', include('AutenticacionApp.urls')),
    
    

    path('', include('FeriaVirtualApp.urls')), 
]

FeriaVirtualApp/urls.py
from django.urls import path

from FeriaVirtualApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('',views.home, name="Home"),
    path('tienda',views.tienda, name="Tienda"),
    path('blog',views.blog, name="Blog"),
    path('contacto',views.contacto, name="Contacto"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

ServiciosApp/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',views.servicios, name="Servicios"),
    
]

FeriaVirtualApp/models.py
from django.db import models

# Create your models here.

ServiciosApp/models.py
from django.db import models

# Create your models here.

class Servicio(models.Model):
    titulo = models.CharField(max_length=50)
    contenido = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='servicios')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'servicio'
        verbose_name_plural = 'servicios'

    def __str__(self):
        return self.titulo

AutenticacionApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User




class CustomUserCreationForm(UserCreationForm):

    #validaciones personalizadas podrían ir aquí

  

    

    class Meta: 
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

AutenticacionApp/views.py
from django.shortcuts import render, redirect, redirect, get_object_or_404

from django.contrib.auth import login, authenticate

from .forms import CustomUserCreationForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.contrib import messages




# Create your views here.

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username = formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request, user)
            #redirigir al Home
            return redirect(to="Home")
        data["form"] = formulario

    return render(request, 'registration/registro.html', data)


@login_required
def lista_usuarios(request):
    usuarios = User.objects.all()
    return render(request, 'registration/lista_usuarios.html', {'usuarios': usuarios})


@login_required
def crear_usuario(request):
    if request.method == 'POST':
        formulario = CustomUserCreationForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, 'Usuario creado con éxito.')
            return redirect('AutenticacionApp:lista_usuarios')
    else:
        formulario = CustomUserCreationForm()
    return render(request, 'registration/formulario_usuario.html', {'formulario': formulario})


@login_required
def actualizar_usuario(request, id_usuario):
    usuario = User.objects.get(pk=id_usuario)
    if request.method == 'POST':
        formulario = CustomUserCreationForm(request.POST, instance=usuario)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "modificado correctamente")
            return redirect(to="AutenticacionApp:lista_usuarios")
    else:
        formulario = CustomUserCreationForm(instance=usuario)
    return render(request, 'registration/formulario_usuario.html', {'formulario': formulario})


def eliminar_usuario(request, id_usuario):
    if request.method == 'GET':
        usuario = get_object_or_404(User, id=id_usuario)
        usuario.delete()
        messages.success(request, 'Usuario eliminado con éxito.')
        return redirect('AutenticacionApp:lista_usuarios')
    
    return redirect('Home')

FeriaVirtualApp/views.py
from django.shortcuts import render, HttpResponse



# Create your views here.

def home(request):

    return render(request, "FeriaVirtualApp/home.html")



def tienda(request):

    return render(request, "FeriaVirtualApp/tienda.html")

def blog(request):

    return render(request, "FeriaVirtualApp/blog.html")

def contacto(request):

    return render(request, "FeriaVirtualApp/contacto.html")

ServiciosApp/views.py
from django.shortcuts import render

from ServiciosApp.models import Servicio

# Create your views here.

def servicios(request):

    servicios=Servicio.objects.all()
    return render(request, "ServiciosApp/servicios.html", {"servicios": servicios})

FeriaVirtualApp/templates/FeriaVirtualApp/base.html
<html>

<head>

{% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'FeriaVirtualApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'FeriaVirtualApp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Feria Virtual</span>
      </h1>

      <div style="text-align: right; margin-right: 100px; color: white;">
      
        {% if user.is_authenticated %}

          Hola {{ user.username }} &nbsp; &nbsp; <a href="{% url 'logout' %}" style="color: white;">Cerrar sesión</a>

        {% else %}

          <a href="{% url 'login' %}" style="color: white;">Login</a> &nbsp; &nbsp; <a href="{% url 'AutenticacionApp:Registro' %}" style="color: white;">Registrate</a>

        {% endif %}

      </div>



 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Home' %}">Feria virtual</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/'%}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Home' %}">Inicio</a>
          </li>
          <!--{% if perms.AutenticacionApp.view_user %}-->
          <li class="nav-item {% if request.path == '/registro/usuarios/'%}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'AutenticacionApp:lista_usuarios' %}">Administración</a>
          </li>
          <!--{% endif %}-->
          <li class="nav-item {% if request.path == '/servicios/'%}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Servicios' %}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path == '/tienda/'%}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Tienda' %}">Tienda</a>
          </li>
          <li class="nav-item {% if request.path == '/contacto/'%}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Contacto' %}">Contacto</a>
          </li>
          <li class="nav-item {% if request.path == '/blog/'%}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Blog' %}">Blog</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>

  <!-- Contenido Cambiante -->


  {% block content%}

  {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Feria Virtual 2023</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    {% if messages %}

    {% for m in messages %}

      <script>

        Swal.fire({
          "title":  "Felicitaciones",
          "text": "{{m}}",
          "icon": "success"
        })
          
      </script>

    {% endfor %}

  {% endif %}

  {% block js%}

  {% endblock %}

  

</body>


</html>

FeriaVirtualApp/templates/FeriaVirtualApp/blog.html
{% extends "FeriaVirtualApp/base.html" %}
   
{% load static %}

{% block content %}

 <html>

    <body>
        
        Blog

        
    </body>


 </html>

{% endblock %}

FeriaVirtualApp/templates/FeriaVirtualApp/contacto.html
{% extends "FeriaVirtualApp/base.html" %}
   
{% load static %}

{% block content %}

 <html>

    <body>
        
        Contacto

        
    </body>


 </html>

{% endblock %}

FeriaVirtualApp/templates/FeriaVirtualApp/home.html
{% extends "FeriaVirtualApp/base.html" %}
   
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
</head>


   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'FeriaVirtualApp/img/Feria virtual frutas.jpeg' %}" alt="" style="width: 670px; height: 600;">
        <!--bolsafrutas3.jpeg, Feria virtual frutas.jpeg, bolsafruta.jpg,local2.jpeg-->
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Calidad</span>
            <span class="section-heading-lower">La mejor fruta</span>
          </h2>
          <p class="mb-3">"¡Del huerto a tu paladar! Disfruta de la frescura y la dulzura de nuestras frutas seleccionadas. 
            Cada bocado es una explosión de sabor natural y salud para ti y tu familia. ¡Ven y descubre la frescura que solo 
            las frutas pueden ofrecer! 🍎🍊🍇 #SaborNaturaleza"
          </p>
         
        </div>
      </div>
    </div>
  </section>
  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">
                "Tu satisfacción es nuestra prioridad absoluta. Con más de 30 años de experiencia en el mundo de las frutas,
                 en Maipo Grande nos comprometemos a brindarte la frescura y calidad que mereces. Desde la plantación hasta
                tu mesa, trabajamos con pasión para llevar la naturaleza directamente a tu hogar, siempre a tiempo y con un servicio
                 profesional impecable. ¡Descubre el sabor auténtico de la naturaleza!" 🍎🍊🍇 #FrescuraGarantizada</p>
            </div>
          </div>
        </div>
      </div>
    </section>
</html>
{% endblock %}

FeriaVirtualApp/templates/FeriaVirtualApp/tienda.html
{% extends "FeriaVirtualApp/base.html" %}
   
{% load static %}

{% block content %}

 <html>

    <body>
        
        Tienda

        
    </body>


 </html>

{% endblock %}

ServiciosApp/templates/ServiciosApp/servicios.html
{% extends "FeriaVirtualApp/base.html" %}
   
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Servicios</title>
</head>



    {% for servicio in servicios%}

        <!-- Heading -->
        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{servicio.imagen.url}}" alt="" style="width: 580px; height: 500;">
                    <!--bolsafrutas3.jpeg, Feria virtual frutas.jpeg, bolsafruta.jpg,local2.jpeg-->
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4" >
                            <span class="section-heading-lower">{{servicio.titulo}}</span>
                            <span class="section-heading-upper">{{servicio.contenido}}</span>
                        </h2>
                    </div>
                </div>
            </div>
        </section>

    {% endfor %}
</html>

{% endblock %}